<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>About Sweater</title>
    <link rel="stylesheet" type="text/css" href="/css/aboutsweater.css">
</head>
<body>

<div class="container">
    <div class="box">
        <div class="content">
            <h2>The Reason of</h2>
            <p>this portfolio-site is showing my skills and abilities</p>
            <p>I have used: Java 8, Spring(Boot, MVC, DATA, Security),
            PostgreSQL, Freemarker, HTML, CSS</p>
            <a href="/">Back To Start Page</a>
        </div>
    </div>
</div>
<svg>
    <filter id="wavy">
        <feTurbulence x="0" y="0" baseFrequency="0.02" numOctaves="5" seed="2">
            <animate attributeName="baseFrequency" dur="60s" values="0.02;0.05;0.02" repeatCount="indefinite"/>
        </feTurbulence>
        <feDisplacementMap in="SourceGraphic" scale="30"/>
    </filter>
</svg>


</body>
</html>