<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Cool Foto</title>
    <link rel="stylesheet" href="/css/coolFoto.css">
</head>
<body>

<div class="container">
    <div class="card">
        <div class="imgBox">
            <img src="/css/bg.jpg"  class="img">
        </div>
        <div class="details">
            <h2>Заголовок (Тег)</h2>
            <p>Текст</p>
        </div>
    </div>

</div>



</body>
</html>