<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="css/registration.css">

    <link href="https://fonts.googleapis.com/css?family=Permanent+Marker" rel="stylesheet">

</head>
<body>

<div class="signup-form">
    <form action="/registration" method="post">
        <h1>Sign Up</h1>

        <input type="text" name="username" placeholder="Full Name" class="txtb">
        <input type="password" name="password" placeholder="Password" class="txtb">

        <input type="email" placeholder="Email" class="txtb">

        <input type="submit" value="Create Account" class="signup-btn">

    </form>
</div>



</body>
</html>