<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="css/resume.css">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <script src="https://kit.fontawesome.com/2ed2e710c7.js"></script>
  <title>Document</title>
</head>
<body>
  <div class="resume-container">

    <div class="sidebar-container jumbotron">
      <img class="main-img"  src="/css/photo.jpg" alt="portrait">
 
      <div class="info">
        <h3 class="sidebar-title">Info</h3>
        <ul class="list-group">
          <li class="list-group-item">
            <i class="side-bar-icon fas fa-mobile-alt"></i>
            Phone: +38(063)695-33-74
          </li>
          <li class="list-group-item">
            <i class="side-bar-icon fas fa-envelope"></i>
            Email: 
            <a class="mail-link" href="http://malozhonvlad@gmail.com">malozhonvlad@gmail.com</a>
          </li>
          <li class="list-group-item">
              <i class="side-bar-icon fas fa-map-marker-alt"></i>
              Location: Kyiv, Ukraine
          </li>
          <li class="list-group-item">
              <i class="side-bar-icon far fa-calendar-alt"></i>
              Date of Birth: 06.10.1989
          </li>
        </ul>
      </div>

      <div class="social">
          <h3 class="sidebar-title">Social</h3>
          <ul class="list-group social-list">
            <li class="list-group-item">
              <a href="https://www.linkedin.com/in/vlad-malozhon-30b2aa182/" class="social-link">
                <i class="side-bar-icon fab fa-linkedin"></i>
                LinkedIn</a>
            </li>
            <li class="list-group-item">
              <a href="https://github.com/MalozhonVlad" class="social-link">
                <i class="side-bar-icon fab fa-github"></i>
                GitHub</a>
            </li>
            <li class="list-group-item">
              <a href="https://www.facebook.com/vlad.malozhon" class="social-link">
                <i class="side-bar-icon fab fa-facebook"></i>
                Facebook</a>
              </li>
<!--            <li class="list-group-item">-->
<!--              <a href="https://www.instagram.com/nekit_park/?hl=uk" class="social-link">-->
<!--                <i class="side-bar-icon fab fa-instagram"></i>-->
<!--                Instagram</a>-->
<!--              </li>-->
          </ul>
  
      </div>

      <div class="languages">
        <h3 class="sidebar-title">Languages</h3>
        <ul class="list-group">

          <li class="list-group-item">
            <div class="lang-container">
              <span>Ukrainian: </span>
              <div class="lang-skill-wrapper">
                <div class="lang-skill-item"></div>
                <div class="lang-skill-item"></div>
                <div class="lang-skill-item"></div>
                <div class="lang-skill-item"></div>
                <div class="lang-skill-item"></div>
              </div>
            </div>
          </li>

          <li class="list-group-item">
            <div class="lang-container">
              <span>Russian: </span>
              <div class="lang-skill-wrapper">
                <div class="lang-skill-item"></div>
                <div class="lang-skill-item"></div>
                <div class="lang-skill-item"></div>
                <div class="lang-skill-item"></div>
                <div class="lang-skill-item"></div>
              </div>
            </div>
          </li>

          <li class="list-group-item">
            <div class="lang-container">
              <span>English: </span>
              <div class="lang-skill-wrapper">
                <div class="lang-skill-item"></div>
                <div class="lang-skill-item"></div>
                <div class="lang-skill-item clean"></div>
                <div class="lang-skill-item clean"></div>
                <div class="lang-skill-item clean"></div>
              </div>
            </div>
          </li>
          
        </ul>
      </div>


    </div>
    <div class="main-info-container">

      <div class="name">
        <h1 class="full-name display-4">Vlad Malozhon</h1>
        <h3 class="position text-muted lead">Java Developer</h3>
      </div>

      <div class="profile">
        <h3 class="about">
          <i class="fas fa-user-circle"></i>
          About me</h3>
        <p class="text-muted">Getting position of <strong>Java Developer</strong>, where I can apply my professional knowledge and skills to designing, developing and deploying the internal and external Java-based solutions.
            In addition, I’m interested in working in a team of professionals with the opportunity of development and growth.
      </div>

      <div class="education">
        <h3 class="education-title">
            <i class="fas fa-graduation-cap"></i>
          Education</h3>
            <h5 class="university">Kyiv National University of Construction and Architecture (KNUBA) 2007-2012</h5>
            <p class="specialty lead">Department of Automation and Information Technology</p>
            <h5 class="university">IT – school Hillel</h5>
            <p class="specialty lead">Science: Back-End developing</p>

      </div>

      <div class="skills">
        <h3 class="skills-title">
          <i class="fas fa-laptop-code"></i>
          Skills</h3>

      <div class="skills-container">

          <ul class="list-group skills-block">
              <li class="list-group-items skills-block-wrap">
                <h6 class="skill-name">Java Core, Java 8</h6>
                <div class="skills-block-item">
                    <div class="block-wrapper"></div>
                    <div class="block-wrapper"></div>
                    <div class="block-wrapper"></div>
                    <div class="block-wrapper"></div>
                    <div class="block-wrapper clean"></div>
                  </div>      
              </li>
              <li class="list-group-items skills-block-wrap">
                <h6 class="skill-name">Spring (Boot, MVC, DATA, AOP, Security)</h6>
                <div class="skills-block-item">
                    <div class="block-wrapper"></div>
                    <div class="block-wrapper"></div>
                    <div class="block-wrapper"></div>
                    <div class="block-wrapper clean"></div>
                    <div class="block-wrapper clean"></div>
                  </div>      
              </li>
              <li class="list-group-items skills-block-wrap">
                  <h6 class="skill-name">REST</h6>
                  <div class="skills-block-item">
                      <div class="block-wrapper"></div>
                      <div class="block-wrapper"></div>
                      <div class="block-wrapper"></div>
                      <div class="block-wrapper clean"></div>
                      <div class="block-wrapper clean"></div>
                  </div>
              </li>
          </ul>

          <ul class="list-group skills-block">
              <li class="list-group-items skills-block-wrap">
                <h6 class="skill-name">ORM(Hibernate), JDBC, MySql, MongoDB</h6>
                <div class="skills-block-item">
                    <div class="block-wrapper"></div>
                    <div class="block-wrapper"></div>
                    <div class="block-wrapper"></div>
                    <div class="block-wrapper clean"></div>
                    <div class="block-wrapper clean"></div>
                </div>      
              </li>
              <li class="list-group-items skills-block-wrap">
                <h6 class="skill-name">Junit, Mockito</h6>
                <div class="skills-block-item">
                    <div class="block-wrapper"></div>
                    <div class="block-wrapper"></div>
                    <div class="block-wrapper"></div>
                    <div class="block-wrapper clean"></div>
                    <div class="block-wrapper clean"></div>
                </div>      
              </li>
              <li class="list-group-items skills-block-wrap">
                  <h6 class="skill-name">HTML,CSS</h6>
                  <div class="skills-block-item">
                      <div class="block-wrapper"></div>
                      <div class="block-wrapper"></div>
                      <div class="block-wrapper clean"></div>
                      <div class="block-wrapper clean"></div>
                      <div class="block-wrapper clean"></div>
                  </div>
              </li>
            </ul>

      </div>

      </div>

      <div class="summary">
        <h3 class="summaty-title">
            <i class="fas fa-user-friends"></i>
            WORK EXPERIENCE
        </h3>
          <p class="text-muted">Junior Java Developer <strong>September 1, 2019 – February 5, 2020 Fintech Trust</strong></p>
          <p class="text-muted">Junior Java Developer <strong>May 26, 2019 – August 22, 2019 Datas Technology</strong></p>
          <p class="text-muted">Junior Java Developer <strong>December, 2018 – May 25, 2019 Fintech Trust</strong></p>
      </div>

      <div class="interests">
        <h3 class="interests-title">
          <i class="fas fa-running"></i>
          Interests</h3>

        <table class="table">
            <tbody>
              <tr>
                <td>Sport</td>
                <td>Traveling</td>
              </tr>
              <tr>
                <td>New Technologies</td>
                <td>Electronic music</td>
              </tr>
            </tbody>
          </table>
      </div>
    </div>
  </div>
</body>
</html>