<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>CSS</title>
    <link href="css/startPage.css" rel="stylesheet" type="text/css"/>
</head>
<body>

<a href="resume">
    <span></span>
    <span></span>
    <span></span>
    <span></span>
    PORTFOLIO
</a>
<a href="aboutsweater">
    <span></span>
    <span></span>
    <span></span>
    <span></span>
    ABOUT SWEATER
</a>

<a href="greeting">
    <span></span>
    <span></span>
    <span></span>
    <span></span>
    LOGIN
</a>

</body>
</html>