create sequence hibernate_sequence start 1 increment 1;

create table message (
        id int8 generated by default as identity not null,
        bytes oid,
        tag varchar(255),
        text varchar(2048) not null,
        user_id int8,
        primary key (id));

create table user_role (
        user_id int8 not null,
        roles varchar(255));

create table usr (
        id int8 not null,
        account_non_expired boolean not null,
        account_non_locked boolean not null,
        activation_code varchar(255),
        credentials_non_expired boolean not null,
        email varchar(255),
        enabled boolean not null,
        password varchar(255) not null,
        password2 varchar(255) not null,
        username varchar(255) not null,
        primary key (id));

alter table if exists message
-- FK70bv6o4exfe3fbrho7nuotopf
        add constraint message_user_fk
        foreign key (user_id) references usr;

alter table if exists user_role
-- FKfpm8swft53ulq2hl11yplpr5
        add constraint user_role_fk
        foreign key (user_id) references usr;